import DestinationPage from '../../../components/DestinationPage';

const data = {
  name: 'האנוי',
  subtitle: 'עיר הבירה המסתורית',
  emoji: '🏛️',
  heroImage: '/images/hanoi.jpg',
  regionName: 'צפון וייטנאם',
  regionHref: '/destinations/north',
  tags: [
    { label: 'עיר בירה', href: '#areas' },
    { label: 'תרבות', href: '#attractions' },
    { label: 'אוכל', href: '#food' },
    { label: 'היסטוריה', href: '#attractions' },
    { label: 'טיולי יום', href: '#daytrips' },
  ],
  chabad: true,
  locationDesc: 'האנוי ממוקמת בצפון וייטנאם, כ-2 שעות מהלונג ביי ו-5-6 שעות מסאפה. שדה תעופה: Noi Bai (HAN)',
  description: 'האנוי היא אחת הערים הוותיקות בדרום-מזרח אסיה, יותר מאלף שנות היסטוריה על שפת נהר האדום. הצרפתים בנו כאן ביולוארדים ואדריכלות קולוניאלית, הוייטנאמים בנו מקדשים ושווקים, ובין שניהם נוצרה עיר שמרגישה כמו הצטלבות בין פריז ואסיה. Old Quarter, 36 הרחובות העתיקים, כל אחד עם מקצוע היסטורי, הוא הלב שאי אפשר לפספס. מסביב: אגמים שקטים, מוזיאוני היסטוריה, מקדש הספרות בן האלף שנה, ורחובות שמתעוררים ב-05:30 עם ריח פו ולא נרדמים לפני חצות. רוב הישראלים ישנים ב-Old Quarter, ויוצאים משם לשאר הצפון.',
  quickStats: [
    { label: 'ימים מומלצים', value: '2–3' },
    { label: 'Grab לשדה תעופה', value: '~250K VND' },
    { label: 'שדה תעופה', value: 'HAN' },
    { label: 'בית חב"ד', value: '✓ פעיל' },
  ],
  attractions: [
    {
      name: 'אגם חרב (Hoan Kiem)',
      href: '/destinations/north/hanoi/hoan-kiem',
      desc: 'לב האנוי, האגם האגדי עם מקדש Ngoc Son הצף על מים ירוקים. בסופי שבוע הרחובות סביב האגם נסגרים לכלי רכב ומתמלאים בילדים, ספורטאים ומוזיקאים. אחת הפינות הכי יפות בוייטנאם.',
      image: '/images/hanoi/hoan-kiem.jpg',
      tip: 'הגיעו ב-06:00–07:00, האנוואים מתאמנים מסביב לאגם ואווירה שקטה לפני ההמונים',
    },
    {
      name: 'Old Quarter, העיר העתיקה',
      href: '/destinations/north/hanoi/old-quarter',
      desc: '36 רחובות עתיקים, כל אחד עם מקצוע היסטורי משלו, רחוב הנחושת, רחוב הנייר, רחוב הבדים. הלב הפועם של האנוי: מסעדות, ברים, הוסטלים וחיי לילה. אפשר לאבד שעות בהליכה רגלית.',
      image: '/images/hanoi/old-quarter.jpg',
      tip: 'טיילו רגלי בלי מפה, כל פינה מגלה משהו חדש. בלילה, Bia Hoi Corner לבירה ב-7 שקל',
    },
    {
      name: 'מקדש הספרות (Temple of Literature)',
      href: '/destinations/north/hanoi/temple-of-literature',
      desc: 'האוניברסיטה הראשונה בוייטנאם מ-1070, מוקדשת לקונפוציוס. חמישה חצרות מרהיבות עם בריכות, עצים עתיקים וסטלות אבן עם שמות בוגרים. שמור טוב יוצא דופן, כאילו הזמן עצר.',
      image: '/images/hanoi/temple-of-literature.jpg',
      tip: 'כניסה: 30,000 VND. הגיעו 08:00–09:00 לפני הסיורים המאורגנים',
    },
    {
      name: 'הו טאי (West Lake)',
      href: '/destinations/north/hanoi/ho-tay',
      desc: 'האגם הגדול של האנוי, 17 ק"מ של שפה מוקפת מסעדות, בתי קפה ומקדשים. שאנטי ורומנטי יותר מ-Old Quarter. בשעות הערב, מסעדות על שפת המים עם תאורה מדהימה.',
      image: '/images/hanoi/ho-tay.jpg',
    },
    {
      name: 'מוזיאון האתנולוגיה',
      href: '/destinations/north/hanoi/ethnology-museum',
      desc: 'אחד ממוזיאוני האתנולוגיה הטובים בדרום-מזרח אסיה, 54 קבוצות אתניות של וייטנאם מוצגות עם בגדים, כלים ובתים מסורתיים בגודל מלא. מרתק גם למי שלא אוהב מוזיאונים.',
      image: '/images/hanoi/ethnology-museum.jpg',
      tip: 'פתוח ש"ב–א, סגור יום שני. כניסה: 40,000 VND. מרוחק מ-Old Quarter, קחו Grab',
    },
    {
      name: 'שוק Dong Xuan',
      href: '/destinations/north/hanoi/dong-xuan',
      desc: 'השוק הגדול והוותיק ביותר של האנוי, שלוש קומות עמוסות בסחורה, בגדים, ירקות וחפצי בית. האטמוספרה המקומית האמיתית, רחוק מהמסלול התיירותי. מיקוח, חובה.',
      image: '/images/hanoi/dong-xuan.jpg',
    },
    {
      name: 'מוזיאון ההיסטוריה הצבאית',
      href: '/destinations/north/hanoi/military-museum',
      desc: 'המוזיאון הצבאי החדש ביותר והגדול בדרום-מזרח אסיה, נפתח בנובמבר 2024. 4 קומות, 12 גלריות, מטוסים וטנקים בחוץ. מקיף, מרשים ושונה מכל מה שראיתם.',
      image: '/images/hanoi/military-museum.png',
      tip: 'ב-Nam Tu Liem, 20 דקות Grab מ-Old Quarter',
    },
    {
      name: 'שכונת הרכבת',
      href: '/destinations/north/hanoi/train-street',
      desc: 'סמטה צרה שמסילת ברזל פעילה עוברת בה ממש בין הבתים — 20 סנטימטר בין הרכבת לחלון. כשהרכבת מגיעה, כולם נצמדים לקיר ומצלמים. תמונה שאי-אפשר לשכוח.',
      image: '/images/hanoi/train-street.jpg',
      tip: 'הרכבת עוברת בערך ב-15:20 וב-19:35, הגיעו 30 דקות מראש',
    },
    {
      name: "מוזיאון הו צ'י מין",
      href: '/destinations/north/hanoi/hcm-museum',
      desc: "3 קומות על חיי אבי האומה הוייטנאמי — מהגלות הצרפתית ועד הניצחון. עיצוב סוריאליסטי מפתיע, מסמכים מקוריים ותמונות נדירות. ממש ליד המאוזוליאום.",
      image: '/images/hanoi/hcm-museum.jpg',
    },
    {
      name: 'סיור אוכל מודרך',
      href: '/destinations/north/hanoi/food-tour',
      desc: '3–4 שעות, 8–10 עצירות, מדריך מקומי שמכיר כל פינה ב-Old Quarter. בון צ\'ה, פה, קפה ביצה, ביה הוי ועוד. הדרך הכי טובה להבין את האנוי דרך הקיבה.',
      image: '/images/hanoi/food-tour.jpg',
      tip: '$25–45, יוצאים בדרך כלל 17:30–18:00. הזמינו מראש',
    },
    {
      name: 'VinWonders Wave Park',
      href: '/destinations/north/hanoi/vinwonders',
      desc: 'פארק המים הגדול בצפון וייטנאם — בריכת גלים של 1.5 מטר, מגלשות, נהר עצלן ואזור ילדים. 20 דקות Grab מהמרכז. מושלם ליום שחם.',
      image: '/images/hanoi/vinwonders.jpg',
      tip: 'כניסה: ~400,000 VND. ימי חול הרבה יותר שקט מסופי שבוע',
    },
  ],
  dayTrips: [
    {
      name: 'הלונג ביי',
      distance: 'כ-170 ק"מ מהאנוי',
      duration: '3.5 שעות נסיעה',
      price: '$50–120 לסיור יום / $150–250 ללילה בספינה',
      desc: 'אחד מאתרי הירושה של אונסק"ו ואחת הנקודות הכי מצולמות בוייטנאם, אלפי צלעות גיר שצומחות ממי הים הירוקים. סיור יום מהאנוי אפשרי, אבל לינה בספינה (cruise) היא חוויה אחרת לגמרי.',
      tip: 'הזמינו דרך ספקים מוכרים בלבד, Indochina Junk, Paradise Cruises. הסיורים הזולים מאוד נוטים לאכזב.',
      mapLink: 'https://www.google.com/maps/search/Ha+Long+Bay+Vietnam',
    },
    {
      name: 'נין בין (Ninh Binh)',
      distance: 'כ-95 ק"מ מהאנוי',
      duration: '2 שעות נסיעה',
      price: '$8–15 אוטובוס / $5–8 Grab',
      desc: 'כינוי: "הלונג ביי על היבשה". שדות אורז ירוקים עם צוקי גיר זקופים, ורידי נהר שחוצים ביניהם בסירת חתירה. טרנג אן (Trang An) הוא אחת החוויות הכי שקטות ויפות בצפון.',
      tip: 'צאו מוקדם, 07:00 לכל היותר. בשעות הצהריים הסיורים מתמלאים ומאבדים מהקסם.',
      mapLink: 'https://www.google.com/maps/search/Ninh+Binh+Vietnam',
    },
    {
      name: 'סאפה',
      distance: 'כ-320 ק"מ מהאנוי',
      duration: '5–6 שעות (אוטובוס לילה / רכבת)',
      price: '$10–20 אוטובוס לילה | $25–40 רכבת',
      desc: 'עיירת הרים בצפון הרחוק, גבול סין. שדות אורז מדורגים שנבנו על הרים תלולים, כפרי מיעוטים אתניים ועמק מוקף ערפל בוקר. הרוב מגיעים לסאפה אוטובוס לילה מהאנוי, שומרים לינה אחת.',
      tip: 'ממליצים על 2 לילות לפחות. הרכבת הלילית מהאנוי היא חוויה בפני עצמה, הזמינו מראש.',
      mapLink: 'https://www.google.com/maps/search/Sapa+Vietnam',
    },
  ],
  food: [
    {
      name: 'Bun Cha',
      desc: 'המנה האנואית הקלאסית, כדורי חזיר וצלעות על גריל, מוגשים בציר מתוק-חמוץ עם אטריות אורז ועשבים. אובמה ואנתוני בורדן אכלו אותה יחד כאן.',
      image: '/images/hanoi/bun-cha.jpg',
      price: '40,000–60,000 VND',
      where: 'Bun Cha Huong Lien, 24 Le Van Huu (מסעדת אובמה)',
    },
    {
      name: 'Pho Bo (פו בקר)',
      desc: 'מרק האטריות המפורסם, האנוי היא עיר מולדתו. הגרסה הצפונית עדינה יותר מהדרומית: ציר צלול, נקי ומתובל בזהירות. ארוחת בוקר קלאסית.',
      image: '/images/hanoi/pho-bo.jpg',
      price: '45,000–80,000 VND',
      where: 'Pho Gia Truyen, 49 Bat Dan, Old Quarter',
    },
    {
      name: 'Egg Coffee (קפה ביצה)',
      desc: 'המצאה האנואית הייחודית, קפה רובוסטה עם קצפת חלמון ביצה. מראה כמו קפוצ\'ינו אבל טעם של קינוח חמים. לא מתגעגעים לאחר שטועמים.',
      image: '/images/hanoi/egg-coffee.jpg',
      price: '30,000–50,000 VND',
      where: 'Cafe Giang, 39 Nguyen Huu Huan (המקום המקורי מ-1946)',
    },
    {
      name: 'Banh Mi',
      desc: 'הכריך הוייטנאמי מבאגט צרפתי עם פטה, נקניק, כבד עוף, ירוקים וצ\'ילי. בהאנוי הגרסה עדינה ומסורתית יותר מהדרום.',
      image: '/images/hanoi/banh-mi.jpg',
      price: '25,000–40,000 VND',
      where: 'Banh Mi 25, 25 Hang Ca, Old Quarter',
    },
    {
      name: 'Sushi Ichi',
      desc: 'המסעדה היפנית הכי מומלצת בהאנוי בקרב ישראלים. לא קלאסי וייטנאמי, אבל אם מתגעגעים לסושי, זה המקום.',
      image: '/images/hanoi/sushi-ichi.jpg',
      where: 'Xuan Dieu St, Tay Ho (West Lake)',
    },
    {
      name: 'סמודי בול',
      desc: 'בולות סמודי בריאות וצבעוניות, מומלצות במיוחד ל-vegan. כמה מקומות ב-Old Quarter.',
      image: '/images/hanoi/smoothie-ball.jpg',
      price: '60,000–90,000 VND',
    },
  ],
  foodTips: [
    'Bun Bo Nam Bo, 67 Hang Dieu: גרסה יבשה של פו, מומלצת מאוד',
    'Good Times Vietnam, Ma May St: המבורגרים, בירה ואווירה טובה לערב',
    'Chops, Hang Buom: מסעדה ישראלית-בינלאומית, מומלצת לגעגוע',
    'חפשו דוכן עמוס מקומיים, סימן לאוכל טרי ואמין',
    'שעות האוכל: ארוחת בוקר 06:00–09:00 (פו ובון צ\'ה), צהריים 11:00–13:00',
  ],
  areas: [
    {
      name: 'Old Quarter (העיר העתיקה)',
      type: 'אזור תיירותי',
      recommended: true,
      desc: 'הלב הפועם של האנוי, רחובות צרים ועמוסים, הוסטלים, מסעדות וחיי לילה. מרחק הליכה מכל האטרקציות. רועש, חי ומלא אנרגיה, רוב הישראלים ישנים כאן.',
    },
    {
      name: 'Hoan Kiem (אגם חרב)',
      type: 'בינוני–יוקרה',
      recommended: true,
      desc: 'שקט יותר מ-Old Quarter, מסביב לאגם המפורסם. מחירים קצת גבוהים יותר אבל נוח ומרכזי. קרוב לסניפי מסעדות איכותיות ולאגם עצמו.',
    },
    {
      name: 'Ba Dinh',
      type: 'היסטורי',
      recommended: false,
      desc: 'האזור הממשלתי-היסטורי עם מוזיאון הו צ\'י מין ומקדש הספרות. לא מומלץ ללינה, שקט מדי בלילה. כדאי לביקור יומי בלבד.',
    },
    {
      name: 'Tay Ho (West Lake)',
      type: 'שקט ומקומי',
      recommended: false,
      desc: 'שכונת עצים ואנשי עסקים מסביב לאגם המערבי. שקט, פחות תיירותי, מסעדות מצוינות על שפת המים. מתאים לשהייה ממושכת יותר.',
    },
  ],
  gettingThere: [
    { from: 'שדה התעופה (Noi Bai)', method: 'Grab בלבד, אל תיכנסו למונית רגילה!', time: '40–60 דקות', icon: '✈️', price: '~250,000 VND', flight: false },
    { from: 'הלונג ביי', method: 'אוטובוס / מיניבוס', time: '3.5 שעות', icon: '🚌', price: '$5–10', flight: false },
    { from: 'סאפה', method: 'אוטובוס לילה / רכבת', time: '5–6 שעות', icon: '🚌', price: '$10–20', flight: false },
    { from: 'נין בין', method: 'אוטובוס / מונית', time: '2 שעות', icon: '🚌', price: '$5–8', flight: false },
    { from: "הא ג'יאנג", method: 'אוטובוס לילה (Vexere)', time: '6–7 שעות', icon: '🚌', price: '$8–12', flight: false },
    { from: 'דה נאנג', method: 'טיסה פנימית', time: '1:15 שעות', icon: '✈️', price: '$25–60', flight: true },
    { from: 'הו צ\'י מין', method: 'טיסה פנימית', time: '2 שעות', icon: '✈️', price: '$30–70', flight: true },
    { from: 'הוי אן', method: 'טיסה לדה נאנג + מונית', time: '1:45 שעות', icon: '✈️', price: '$30–65', flight: true },
  ],
  localTransport: [
    'Grab, האפליקציה החיונית, מחיר קבוע. גם אופנוע (Grab Bike) וגם מונית (Grab Car)',
    'הליכה, Old Quarter קטן מספיק להליכה בין כל האטרקציות',
    'אופניים חשמליים, השכרה ~100,000 VND/יום. כיף לאגם המערבי',
    'אל תיכנסו למונית ללא מד, תמחור תיירות בלי ברירה',
  ],
  accommodation: [
    {
      type: 'תקציב נמוך, הוסטל',
      price: '150K–500K VND/לילה',
      desc: 'דורמס ממוצע $5–8, חדר זוגי פרטי $15–25. Old Quarter מלא הוסטלים מצוינים.',
      places: [
        { name: 'The Charming Hostel', note: 'חדר זוגי ~500K VND, "סבבה לגמרי"', mapLink: 'https://www.google.com/maps/search/The+Charming+Hostel+Hanoi' },
        { name: 'Awesome Hostel', note: 'דורמס מומלצים, אווירה טובה', mapLink: 'https://www.google.com/maps/search/Awesome+Hostel+Hanoi' },
        { name: 'Vietnam Backpacker Hostel', note: 'מרכזי, עם בר, ישראלים רבים', mapLink: 'https://www.google.com/maps/search/Vietnam+Backpacker+Hostel+Hanoi' },
      ],
    },
    {
      type: 'תקציב בינוני, מלון בוטיק',
      price: '$20–55/לילה',
      desc: 'מלונות בוטיק ב-Old Quarter ו-Hoan Kiem, AC, WiFi ולעיתים ארוחת בוקר.',
      places: [
        { name: "La Ava's Home", note: 'מומלצת ביותר, אווירה ביתית', mapLink: "https://www.google.com/maps/search/La+Ava+Home+Hanoi" },
        { name: 'Hanoi La Siesta Hotel', note: 'שירות מצוין, ארוחת בוקר כלולה', mapLink: 'https://www.google.com/maps/search/Hanoi+La+Siesta+Hotel' },
        { name: 'án Hostel & Hotel', note: 'עיצוב יפה, מרכזי', mapLink: 'https://www.google.com/maps/search/an+Hostel+Hotel+Hanoi' },
      ],
    },
    {
      type: 'תקציב גבוה, 4–5 כוכבים',
      price: '$70–200+/לילה',
      desc: 'מלונות עם בריכה, ספא ושירות מלא. חלקם בנויים בבנייני קולוניאל צרפתי מרהיבים.',
      places: [
        { name: 'The Oriental Jade Hotel & Spa', note: 'בוטיק יוקרה ב-Old Quarter', mapLink: 'https://www.google.com/maps/search/Oriental+Jade+Hotel+Hanoi' },
        { name: 'Sofitel Legend Metropole', note: 'המלון ההיסטורי המפורסם של האנוי', mapLink: 'https://www.google.com/maps/search/Sofitel+Metropole+Hanoi' },
      ],
    },
  ],
  seasons: [
    {
      months: 'נובמבר – פברואר',
      icon: '🌤️',
      best: true,
      desc: 'הזמן הטוב ביותר, יבש, מגניב (15–22°C). מושלם להליכה. לפעמים ערפילי, אבל לא חם ולא גשום. פסח ביינואר/פברואר, Chabad מאוד פעיל.',
    },
    {
      months: 'מרץ – אפריל',
      icon: '🌸',
      best: false,
      desc: 'מתחמם בהדרגה (22–28°C). עדיין נעים, מעט גשמים מדי פעם. עונה טובה.',
    },
    {
      months: 'מאי – ספטמבר',
      icon: '🌧️',
      best: false,
      desc: 'עונת גשמים וחום (30–36°C). גשמי טרופים כמעט כל יום בשעות אחר הצהריים. אפשרי אבל פחות נוח. המחירים יורדים.',
    },
    {
      months: 'אוקטובר',
      icon: '🍂',
      best: false,
      desc: 'עדיין יכול להיות גשום בתחילת החודש, מתייבש לקראת סופו. מעבר לעונה הטובה.',
    },
  ],
  travelerTypes: [
    {
      type: 'סולו',
      icon: '🎒',
      desc: 'מושלם. Old Quarter מלא ישראלים, קל מאוד להכיר אנשים בהוסטלים. חיי לילה, טיולים ספונטניים ורחובות שאפשר לאבד בהם שעות.',
    },
    {
      type: 'זוגות',
      icon: '❤️',
      desc: 'מצוין. ערבי אגם חרב רומנטיים, ארוחות ב-West Lake, טיול בין הרחובות העתיקים. אל תפספסו קפה ביצה בשעות הערב.',
    },
    {
      type: 'משפחות',
      icon: '👨‍👩‍👧',
      desc: 'טוב, עם הסתייגות אחת: התנועה סוערת ורועשת, ילדים קטנים צריכים תשומת לב בחציית כביש. מוזיאון האתנולוגיה מעולה לילדים מגיל 8+.',
    },
  ],
  tips: [
    'החלפת כסף: חנות זהב ב-130 Hang Bac, שערים טובים מהבנק',
    '2–3 ימים מספיקים לרוב האטרקציות. יומיים אם ממהרים',
    'VPBank, כספומט עם עמלות נמוכות יחסית',
    'SIM: לא לקנות בשדה תעופה, קנו ב-Viettel בעיר',
    'חציית כביש: לכו בקצב קבוע ואל תעצרו פתאום, הרכבים עוקפים סביבכם',
    'שעות עומס: 07:00–09:00 ו-17:00–19:00, עדיף ללכת ברגל',
    'Beer Hoi (bia hoi), בירה מקומית טרייה ב-7,000 VND. Bia Hoi Corner בצומת Luong Ngoc Quyen',
    'בית חב"ד: WhatsApp +84-83-872-8225 | jewishhanoi.com',
  ],
  chabadInfo: [
    'בית חב"ד האנוי, Old Quarter',
    'WhatsApp: +84-83-872-8225 | אתר: jewishhanoi.com',
    'ארוחות שישי ושבת, חגים, מידע לתיירים',
  ],
  nextDest: { name: "הא ג'יאנג", href: '/destinations/north/ha-giang' },
};

export default function HanoiPage() {
  return <DestinationPage dest={data} />;
}
